# This workflow represents the continuous integration pipeline for the samply/tomcat-common docker image

name: Build, Test and Deploy samply/tomcat-common

on:
  schedule:
    - cron: '0 8 * * *' # everyday at 8am
  push:
    branches: ["main", "develop"]
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            "samply/tomcat-common"
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tomcat/Dockerfile
          load: true
          tags: tomcat-common

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tomcat-common'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          file: ./tomcat/Dockerfile
          push: true
          platforms: "linux/amd64,linux/arm64/v8"
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: ${{ steps.docker-meta.outputs.tags }}
